"Name: \PR:CL_WDR_VALUE_HELP_HANDLER=====CP\TY:LCL_DDIC_SUGGEST_HANDLER_2\ME:GET_RESULT_AS_JSON\SE:BEGIN\EI
ENHANCEMENT 0 ZE_ARSH_CL_WDR_VALUE_HELP_HAND.
* bug fix.
    m_shlp = c_shlp.
ENDENHANCEMENT.
