"Name: \PR:SAPLSDHI\FO:SET_HELP_INFO_FROM_FOCUS\SE:END\EI
ENHANCEMENT 0 ZE_ARSH_SDHI.
* MEMORY ID 'CALLFIELD'.
  CALL FUNCTION 'ZARSH_EXPORT_CALLFIELD'
    CHANGING
      help_info = help_info.

ENDENHANCEMENT.
