"Name: \TY:CL_WD_FREE_VALUE_SUGGEST_UTIL\ME:EXECUTE_SUGGEST\SE:BEGIN\EI
ENHANCEMENT 0 ZE_ARSH_CL_WD_FREE_VALUE_SUG_U.
* MEMORY ID 'CALLFIELD'.
  CALL FUNCTION 'ZARSH_EXPORT_CALLFIELD'
    EXPORTING
      is_definition = is_definition.

ENDENHANCEMENT.
